### ISSUE TITLE
Add number of satellites to status message

### ISSUE THREAD

**Issue by redercj** [redercj/LightAPRS-1.0#3]
If we can only send the status message due to not having GPS lock, it may be good to know how many satellites we are locked to.

**Comment by quantumbagel** [comment]
Sorry, but this is already in the code. 

`sprintf(StatusMessage, "txCnt %03d satCnt %02d alt %06ul", TxCount, (int)gps.satellites.value(), (long)gps.altitude.feet());`(line 565)


`SatCnt` corresponds to `gps.satellites.value()` which is the satellite count.

However, lines have been added to ensure that it is called every 15 minutes outside GPS lock.
